# Generated by Django 3.0.8 on 2020-07-08 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
